# Vulcan Office brand overlay for the Euro-Office DocumentServer bake.
#
# Appended after the upstream ./docker-bake.hcl on the bake command line:
#
#   docker buildx bake -f ./docker-bake.hcl \
#                      -f ./brands/vulcan-office-brand/brand-server.hcl \
#                      brand-icons packages standalone
#
# Brand *values* (COMPANY_NAME, PRODUCT_NAME, PUBLISHER_*, THEME) are NOT redefined
# here: the upstream bake file already declares them as `variable` blocks with
# Euro-Office defaults, and buildx overrides any such variable from the environment.
# CI exports them from brand/brand.env, which keeps one source of truth.
#
# CAREFUL -- bake MERGES target fields across files, it does not replace targets.
# The upstream brand-icons target is `dockerfile-inline = "FROM scratch\nWORKDIR /keep"`
# (an empty image, which is what makes the default Euro-Office brand apply). Setting
# only `dockerfile` here would leave that inline definition in place, and because
# dockerfile-inline wins over dockerfile the overlay would be silently dropped and the
# build would come out unbranded. So we override dockerfile-inline itself.

target "brand-icons" {
  context = "./brands/vulcan-office-brand"

  # A scratch image whose root mirrors the DocumentServer repo layout. The upstream
  # Dockerfiles overlay it onto the build tree with an optional COPY:
  #
  #   server/.docker/server.bake.Dockerfile:50
  #     COPY --from=brand-icons /[s]erver /server/
  #   document-server-integration/.docker/example.bake.Dockerfile:29
  #     COPY --from=brand-icons /[d]ocument-server-integration/.../nodejs /app/
  #   build/.docker/packages.bake.Dockerfile:51
  #     COPY --from=brand-icons /[d]ocument-server-package /document-server-package/
  #
  # The `/[s]erver` bracket glob makes each COPY a no-op when the path is absent, so a
  # brand only ships the trees it actually overrides.
  #
  # overlay/ is generated by scripts/rebrand.sh -- do not hand-edit it.
  dockerfile-inline = "FROM scratch\nCOPY overlay/ /\n"
}
