# Vulcan Office brand overlay for the Euro-Office DocumentServer bake.
#
# Appended after the upstream ./docker-bake.hcl on the bake command line:
#
#   docker buildx bake -f ./docker-bake.hcl \
#                      -f ./brands/vulcan-office-brand/brand-server.hcl \
#                      brand-icons packages standalone
#
# Brand *values* (COMPANY_NAME, PRODUCT_NAME, PUBLISHER_*, THEME) are NOT redefined
# here: the upstream bake file already declares them as `variable` blocks with
# Euro-Office defaults, and buildx overrides any such variable from the environment.
# CI exports them from brand/brand.env, which keeps one source of truth.
#
# CAREFUL -- bake MERGES target fields across files, it does not replace targets.
# The upstream brand-icons target is `dockerfile-inline = "FROM scratch\nWORKDIR /keep"`
# (an empty image, which is what makes the default Euro-Office brand apply). Setting
# only `dockerfile` here would leave that inline definition in place, and because
# dockerfile-inline wins over dockerfile the overlay would be silently dropped and the
# build would come out unbranded. So we override dockerfile-inline itself.

# Select our theme for the web-apps build.
#
# Upstream hardcodes `THEME=euro-office` in web-apps/.docker/web-apps.bake.Dockerfile;
# scripts/rebrand.sh turns it into an ARG so this can override it. Without BOTH halves
# the editor builds green and unbranded -- the theme directory is present, and simply
# never selected.
#
# Only THEME is needed: web-apps/build/theme.config.mjs resolves each brand token as
# `env var > theme/<THEME>/meta/config.json > ONLYOFFICE default`, and our config.json
# already carries company_name, publisher_url, attribution and the logo names.
target "web-apps" {
  args = {
    THEME = "vulcan-office"

    # The deployed HTML carries three brand tokens that upstream v9.3.2 stopped
    # substituting (see the deploy-html.js note in scripts/rebrand.sh). We substitute
    # them ourselves, so they have to be passed in.
    #
    # The names describe the LOGO's colour, not the theme's: the loader on a light
    # background needs the DARK logo, and vice versa. Getting these backwards yields an
    # invisible splash logo -- white on white -- which no test catches.
    APP_TITLE_TEXT   = "Vulcan Office"
    LOADER_LOGO      = "dark-logo_s.svg"    # on light background
    LOADER_LOGO_DARK = "header-logo_s.svg"  # white logo, on dark background
  }
}

target "brand-icons" {
  context = "./brands/vulcan-office-brand"

  # A scratch image whose root mirrors the DocumentServer repo layout. The upstream
  # Dockerfiles overlay it onto the build tree with an optional COPY:
  #
  #   server/.docker/server.bake.Dockerfile:50
  #     COPY --from=brand-icons /[s]erver /server/
  #   document-server-integration/.docker/example.bake.Dockerfile:29
  #     COPY --from=brand-icons /[d]ocument-server-integration/.../nodejs /app/
  #   build/.docker/packages.bake.Dockerfile:51
  #     COPY --from=brand-icons /[d]ocument-server-package /document-server-package/
  #
  # The `/[s]erver` bracket glob makes each COPY a no-op when the path is absent, so a
  # brand only ships the trees it actually overrides.
  #
  # overlay/ is generated by scripts/rebrand.sh -- do not hand-edit it.
  dockerfile-inline = "FROM scratch\nCOPY overlay/ /\n"
}
